#!/usr/bin/env python3
"""Validate a Visual Pack ZIP attached to a GitHub submission issue.

The package format is intentionally strict: exactly visualpack.json plus the
14 JPG files generated by Aniki Visual Pack Creator. Any extra entry, folder,
duplicate, renamed image, or missing file rejects the submission.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path

EXPECTED_IMAGES = {
    "MainBackground.jpg": (1920, 1080),
    "Welcome.jpg": (1920, 1080),
    "StatView.jpg": (1920, 1080),
    "FriendsView.jpg": (1920, 1080),
    "AchievementsView.jpg": (1920, 1080),
    "MediaView.jpg": (1920, 1080),
    "StoreView.jpg": (1920, 1080),
    "MainMenu.jpg": (531, 986),
    "SettingsBackground.jpg": (487, 1080),
    "FrameSettingsBackground.jpg": (1247, 900),
    "MessageBox.jpg": (830, 429),
    "GameMenu.jpg": (470, 655),
    "ItemMenu.jpg": (503, 818),
    "Login.jpg": (857, 238),
}
EXPECTED_FILES = set(EXPECTED_IMAGES) | {"visualpack.json"}
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")
PACK_ID = re.compile(r"^[A-Za-z0-9._-]+$")
MARKDOWN_ZIP_LINK = re.compile(r"\[([^\]]+\.zip)\]\((https://[^)\s]+)\)", re.IGNORECASE)
RAW_ZIP_URL = re.compile(r"https://[^\s<>()\]]+\.zip(?:\?[^\s<>()\]]*)?", re.IGNORECASE)
ALLOWED_DOWNLOAD_HOSTS = {"github.com", "raw.githubusercontent.com", "objects.githubusercontent.com", "user-attachments.githubusercontent.com"}
MAX_DOWNLOAD_BYTES = 250 * 1024 * 1024
MAX_UNCOMPRESSED_BYTES = 500 * 1024 * 1024


class ValidationError(Exception):
    pass


def fail(message: str) -> None:
    raise ValidationError(message)


def extract_zip_url(issue_body: str) -> tuple[str, str]:
    section_match = re.search(
        r"###\s+Visual Pack ZIP\s*\n(.*?)(?=\n###\s+|\Z)",
        issue_body,
        flags=re.IGNORECASE | re.DOTALL,
    )
    haystack = section_match.group(1) if section_match else issue_body

    candidates: list[tuple[str, str]] = []
    for label, url in MARKDOWN_ZIP_LINK.findall(haystack):
        candidates.append((label, url))
    for url in RAW_ZIP_URL.findall(haystack):
        if not any(existing_url == url for _, existing_url in candidates):
            name = Path(urllib.parse.urlparse(url).path).name or "submission.zip"
            candidates.append((name, url))

    if not candidates:
        fail("No .zip attachment or direct .zip link was found in the 'Visual Pack ZIP' field.")
    if len(candidates) != 1:
        names = ", ".join(name for name, _ in candidates)
        fail(f"Exactly one Visual Pack ZIP must be attached. Found {len(candidates)}: {names}")

    name, url = candidates[0]
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https":
        fail("The ZIP download link must use HTTPS.")
    host = (parsed.hostname or "").lower()
    if host not in ALLOWED_DOWNLOAD_HOSTS and not host.endswith(".githubusercontent.com"):
        fail("For automatic validation, attach the ZIP directly to the GitHub issue instead of using an external host.")
    return name, url


def download(url: str, destination: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": "AnikiCommunityVisualPacks-Validator/1.0"})
    try:
        with urllib.request.urlopen(request, timeout=60) as response, destination.open("wb") as output:
            total = 0
            while True:
                chunk = response.read(1024 * 1024)
                if not chunk:
                    break
                total += len(chunk)
                if total > MAX_DOWNLOAD_BYTES:
                    fail("The submitted ZIP is too large for automatic validation (maximum 250 MB).")
                output.write(chunk)
    except ValidationError:
        raise
    except Exception as exc:
        fail(f"Could not download the submitted ZIP: {exc}")


def jpeg_dimensions(stream) -> tuple[int, int]:
    if stream.read(2) != b"\xff\xd8":
        fail("Image is not a valid JPEG file.")

    while True:
        prefix = stream.read(1)
        if not prefix:
            fail("JPEG ended before image dimensions were found.")
        if prefix != b"\xff":
            continue

        marker = stream.read(1)
        while marker == b"\xff":
            marker = stream.read(1)
        if not marker:
            fail("Invalid JPEG marker.")

        marker_value = marker[0]
        if marker_value in {0xD8, 0xD9} or 0xD0 <= marker_value <= 0xD7:
            continue

        length_bytes = stream.read(2)
        if len(length_bytes) != 2:
            fail("Invalid JPEG segment length.")
        segment_length = int.from_bytes(length_bytes, "big")
        if segment_length < 2:
            fail("Invalid JPEG segment.")

        sof_markers = {
            0xC0, 0xC1, 0xC2, 0xC3,
            0xC5, 0xC6, 0xC7,
            0xC9, 0xCA, 0xCB,
            0xCD, 0xCE, 0xCF,
        }
        if marker_value in sof_markers:
            data = stream.read(segment_length - 2)
            if len(data) < 5:
                fail("Invalid JPEG size segment.")
            height = int.from_bytes(data[1:3], "big")
            width = int.from_bytes(data[3:5], "big")
            return width, height

        stream.seek(segment_length - 2, 1)


def validate_zip(zip_path: Path) -> dict[str, str]:
    try:
        archive = zipfile.ZipFile(zip_path, "r")
    except Exception as exc:
        fail(f"The submitted file is not a valid ZIP archive: {exc}")

    with archive:
        bad_crc = archive.testzip()
        if bad_crc:
            fail(f"ZIP integrity check failed for: {bad_crc}")

        infos = archive.infolist()
        if not infos:
            fail("The ZIP is empty.")

        names = [info.filename for info in infos]
        if len(names) != len(set(names)) or len(names) != len({name.casefold() for name in names}):
            fail("The ZIP contains duplicate file names.")

        for info in infos:
            name = info.filename
            if info.is_dir() or "/" in name or "\\" in name or name in {".", ".."} or ".." in Path(name).parts:
                fail(f"Folders and nested paths are not allowed: {name}")
            unix_mode = (info.external_attr >> 16) & 0o170000
            if unix_mode == 0o120000:
                fail(f"Symbolic links are not allowed: {name}")
            if info.flag_bits & 0x1:
                fail(f"Encrypted ZIP entries are not allowed: {name}")

        actual = set(names)
        missing = sorted(EXPECTED_FILES - actual)
        extra = sorted(actual - EXPECTED_FILES)
        if missing:
            fail("Missing required file(s): " + ", ".join(missing))
        if extra:
            fail("Unexpected file(s) found: " + ", ".join(extra))
        if len(infos) != len(EXPECTED_FILES):
            fail(f"The ZIP must contain exactly {len(EXPECTED_FILES)} files.")

        uncompressed_total = sum(info.file_size for info in infos)
        if uncompressed_total > MAX_UNCOMPRESSED_BYTES:
            fail("The uncompressed package is unexpectedly large.")

        for file_name, expected_size in EXPECTED_IMAGES.items():
            with archive.open(file_name, "r") as image_stream:
                actual_size = jpeg_dimensions(image_stream)
            if actual_size != expected_size:
                fail(
                    f"{file_name} has invalid dimensions: "
                    f"{actual_size[0]}x{actual_size[1]} (expected {expected_size[0]}x{expected_size[1]})."
                )

        try:
            manifest = json.loads(archive.read("visualpack.json").decode("utf-8-sig"))
        except Exception as exc:
            fail(f"visualpack.json is invalid: {exc}")

        if not isinstance(manifest, dict):
            fail("visualpack.json must contain a JSON object.")
        if manifest.get("formatVersion") != 1:
            fail("visualpack.json formatVersion must be 1.")

        pack_id = str(manifest.get("id", "")).strip()
        name = str(manifest.get("name", "")).strip()
        author = str(manifest.get("author", "")).strip()
        version = str(manifest.get("version", "")).strip()
        if not pack_id or not PACK_ID.fullmatch(pack_id):
            fail("visualpack.json contains an invalid or missing pack ID.")
        if not name:
            fail("visualpack.json contains an empty pack name.")
        if not SEMVER.fullmatch(version):
            fail("visualpack.json contains an invalid semantic version.")

        return {
            "id": pack_id,
            "name": name,
            "author": author or "(not specified)",
            "version": version,
        }


def write_report(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--zip", type=Path, help="Validate a local ZIP instead of a GitHub issue attachment.")
    parser.add_argument("--issue-body-env", default="ISSUE_BODY", help="Environment variable containing the GitHub issue body.")
    parser.add_argument("--report", type=Path, default=Path("submission-validation.txt"))
    args = parser.parse_args()

    try:
        if args.zip:
            package_name = args.zip.name
            zip_path = args.zip
            if not zip_path.is_file():
                fail(f"ZIP not found: {zip_path}")
            metadata = validate_zip(zip_path)
        else:
            issue_body = os.environ.get(args.issue_body_env, "")
            if not issue_body.strip():
                fail("GitHub issue body is empty.")
            package_name, url = extract_zip_url(issue_body)
            with tempfile.TemporaryDirectory(prefix="aniki-vp-") as temp_dir:
                zip_path = Path(temp_dir) / "submission.zip"
                download(url, zip_path)
                metadata = validate_zip(zip_path)

        report = [
            "VALIDATION PASSED",
            f"Package: {package_name}",
            f"ID: {metadata['id']}",
            f"Name: {metadata['name']}",
            f"Author: {metadata['author']}",
            f"Version: {metadata['version']}",
            f"Files: {len(EXPECTED_FILES)}/{len(EXPECTED_FILES)} expected files only",
        ]
        write_report(args.report, report)
        print("\n".join(report))
        return 0
    except ValidationError as exc:
        report = ["VALIDATION FAILED", str(exc)]
        write_report(args.report, report)
        print("\n".join(report), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
